version: '3'

services:
  gateway:
    build: 'packages/gateway'
    ports:
      - "5000:80"
  auth:
    build: 'packages/auth'
    ports:
      - "5001:80"
  orders:
    build: 'packages/orders'
    ports:
      - "5002:80"
  shipping:
    build: 'packages/shipping'
    ports:
      - "5003:80"

  jaeger:
    image: jaegertracing/all-in-one:1.20
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "14250:14250"
      - "9411:9411"
     